//// <auto-generated />
//using System;
//using Application.Infrastructure.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace Application.Infrastructure.Migrations
//{
//    [DbContext(typeof(ApplicationDBContext))]
//    [Migration("20231106063247_AddDatabaseAndTables")]
//    partial class AddDatabaseAndTables
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.13")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Application.Data.Entities.Complaint", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("File")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Type")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("UserId")
//                        .IsRequired()
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("Complaints");
//                });

//            modelBuilder.Entity("Application.Data.Entities.Demand", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int?>("CompId")
//                        .HasColumnType("int");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("CompId");

//                    b.ToTable("Demands");
//                });

//            modelBuilder.Entity("Application.Data.Entities.User", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("FName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("File")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("LName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Password")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Role")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Users");
//                });

//            modelBuilder.Entity("Application.Data.Entities.Complaint", b =>
//                {
//                    b.HasOne("Application.Data.Entities.User", "user")
//                        .WithMany("Complaints")
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("user");
//                });

//            modelBuilder.Entity("Application.Data.Entities.Demand", b =>
//                {
//                    b.HasOne("Application.Data.Entities.Complaint", "Complaint")
//                        .WithMany("Demands")
//                        .HasForeignKey("CompId");

//                    b.Navigation("Complaint");
//                });

//            modelBuilder.Entity("Application.Data.Entities.Complaint", b =>
//                {
//                    b.Navigation("Demands");
//                });

//            modelBuilder.Entity("Application.Data.Entities.User", b =>
//                {
//                    b.Navigation("Complaints");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
